name: Trajectory
version: '1.0-SNAPSHOT'
main: org.mingzu.trajectory.Trajectory
api-version: '1.20'
load: STARTUP
authors: [ MingZu ]
description: Trajectory
commands:
  trajectory:
    description: Bật tắt hack nhìn đường đạn
    usage: /trajectory <on/off>
permissions:
  trajectory.use:
    description: Turn Trajectory on/off
    default: op
  trajectory.admin:
    description: Access to all commands
    default: op